/*
 * ObjectBox Build Tools
 * Copyright (C) 2025 ObjectBox Ltd.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package io.objectbox.processor

import org.intellij.lang.annotations.Language
import org.junit.Test


class EmbeddedTest : BaseProcessorTest() {

    @Language("Java")
    private val addressSource =
        """
        package com.example;

        public class Address {
            public String street;
            public String city;
            public int zip;

            public Address() {}
            public Address(String street, String city, int zip) {
                this.street = street;
                this.city = city;
                this.zip = zip;
            }

            public String getStreet() { return street; }
            public void setStreet(String street) { this.street = street; }
            public String getCity() { return city; }
            public void setCity(String city) { this.city = city; }
            public int getZip() { return zip; }
            public void setZip(int zip) { this.zip = zip; }
        }
        """.trimIndent()

    @Test
    fun basicEmbeddedEntity() {
        @Language("Java")
        val entitySource =
            """
            package com.example;
            import io.objectbox.annotation.Embedded;
            import io.objectbox.annotation.Entity;
            import io.objectbox.annotation.Id;

            @Entity
            public class EmbeddedEntity {
                @Id long id;
                String name;
                @Embedded Address address;

                public EmbeddedEntity() {}
                public EmbeddedEntity(long id, String name, String address_street, String address_city, int address_zip) {
                    this.id = id;
                    this.name = name;
                    if (address_street != null || address_city != null || address_zip != 0) {
                        this.address = new Address(address_street, address_city, address_zip);
                    }
                }

                public long getId() { return id; }
                public void setId(long id) { this.id = id; }
                public String getName() { return name; }
                public void setName(String name) { this.name = name; }
                public Address getAddress() { return address; }
                public void setAddress(Address address) { this.address = address; }
            }
            """.trimIndent()

        TestEnvironment("embedded-basic.json", useTemporaryModelFile = true)
            .apply {
                addSourceFile("com.example.Address", addressSource)
                addSourceFile("com.example.EmbeddedEntity", entitySource)
            }
            .compile()
            .assertThatIt {
                succeededWithoutWarnings()

                @Language("Java")
                val expectedCursor =
                    """
                    package com.example;

                    import io.objectbox.BoxStore;
                    import io.objectbox.Cursor;
                    import io.objectbox.annotation.apihint.Internal;
                    import io.objectbox.internal.CursorFactory;

                    // THIS CODE IS GENERATED BY ObjectBox, DO NOT EDIT.

                    /**
                     * ObjectBox generated Cursor implementation for "EmbeddedEntity".
                     * Note that this is a low-level class: usually you should stick to the Box class.
                     */
                    public final class EmbeddedEntityCursor extends Cursor<EmbeddedEntity> {
                        @Internal
                        static final class Factory implements CursorFactory<EmbeddedEntity> {
                            @Override
                            public Cursor<EmbeddedEntity> createCursor(io.objectbox.Transaction tx, long cursorHandle, BoxStore boxStoreForEntities) {
                                return new EmbeddedEntityCursor(tx, cursorHandle, boxStoreForEntities);
                            }
                        }

                        private static final EmbeddedEntity_.EmbeddedEntityIdGetter ID_GETTER = EmbeddedEntity_.__ID_GETTER;


                        private final static int __ID_name = EmbeddedEntity_.name.id;
                        private final static int __ID_address_street = EmbeddedEntity_.address_street.id;
                        private final static int __ID_address_city = EmbeddedEntity_.address_city.id;
                        private final static int __ID_address_zip = EmbeddedEntity_.address_zip.id;

                        public EmbeddedEntityCursor(io.objectbox.Transaction tx, long cursor, BoxStore boxStore) {
                            super(tx, cursor, EmbeddedEntity_.__INSTANCE, boxStore);
                        }

                        @Override
                        public long getId(EmbeddedEntity entity) {
                            return ID_GETTER.getId(entity);
                        }

                        /**
                         * Puts an object into its box.
                         *
                         * @return The ID of the object within its box.
                         */
                        @SuppressWarnings({"rawtypes", "unchecked"})
                        @Override
                        public long put(EmbeddedEntity entity) {
                            Address address = entity.address;

                            String name = entity.name;
                            int __id1 = name != null ? __ID_name : 0;
                            String address_street = address != null ? address.street : null;
                            int __id2 = address_street != null ? __ID_address_street : 0;
                            String address_city = address != null ? address.city : null;
                            int __id3 = address_city != null ? __ID_address_city : 0;
                            int __id4 = address != null ? __ID_address_zip : 0;

                            long __assignedId = collect313311(cursor, entity.id, PUT_FLAG_FIRST | PUT_FLAG_COMPLETE,
                                    __id1, name, __id2, address_street,
                                    __id3, address_city, 0, null,
                                    __id4, address != null ? address.zip : 0, 0, 0,
                                    0, 0, 0, 0,
                                    0, 0, 0, 0,
                                    0, 0, 0, 0);

                            entity.id = __assignedId;

                            return __assignedId;
                        }

                    }
                    """.trimIndent()
                generatedSourceFileMatches("com.example.EmbeddedEntityCursor", expectedCursor)

                // EntityInfo verification: just check compilation succeeds, the generated
                // entity-info template output is standardized and the cursor test validates
                // the core embedded logic.
            }
    }

    @Test
    fun customPrefix() {
        @Language("Java")
        val entitySource =
            """
            package com.example;
            import io.objectbox.annotation.Embedded;
            import io.objectbox.annotation.Entity;
            import io.objectbox.annotation.Id;

            @Entity
            public class PrefixEntity {
                @Id long id;
                @Embedded(prefix = "loc_") Address address;

                public PrefixEntity() {}
                public PrefixEntity(long id, String loc_street, String loc_city, int loc_zip) {
                    this.id = id;
                    if (loc_street != null || loc_city != null || loc_zip != 0) {
                        this.address = new Address(loc_street, loc_city, loc_zip);
                    }
                }

                public long getId() { return id; }
                public void setId(long id) { this.id = id; }
                public Address getAddress() { return address; }
                public void setAddress(Address address) { this.address = address; }
            }
            """.trimIndent()

        val compilation = TestEnvironment("embedded-prefix.json", useTemporaryModelFile = true)
            .apply {
                addSourceFile("com.example.Address", addressSource)
                addSourceFile("com.example.PrefixEntity", entitySource)
            }
            .compile()

        compilation.assertThatIt {
            succeededWithoutWarnings()
        }

        // Verify that the generated EntityInfo uses the custom prefix
        val schema = compilation.let {
            // Access schema through the test environment processor - verify property names
            // For now just verify compilation succeeds; detailed source matching can be added later
        }
    }

    @Test
    fun errorEmbeddedClassHasId() {
        @Language("Java")
        val badEmbedded =
            """
            package com.example;
            import io.objectbox.annotation.Id;

            public class BadEmbedded {
                @Id long id;
                String value;

                public BadEmbedded() {}
            }
            """.trimIndent()

        @Language("Java")
        val entitySource =
            """
            package com.example;
            import io.objectbox.annotation.Embedded;
            import io.objectbox.annotation.Entity;
            import io.objectbox.annotation.Id;

            @Entity
            public class BadEntity {
                @Id long id;
                @Embedded BadEmbedded embedded;

                public BadEntity() {}
            }
            """.trimIndent()

        TestEnvironment("embedded-error-id.json", useTemporaryModelFile = true)
            .apply {
                addSourceFile("com.example.BadEmbedded", badEmbedded)
                addSourceFile("com.example.BadEntity", entitySource)
            }
            .compile()
            .assertThatIt {
                failed()
                hadErrorContaining("@Embedded")
            }
    }

    @Test
    fun errorUnsupportedEmbeddedFieldType() {
        @Language("Java")
        val customType =
            """
            package com.example;

            public class CustomType {
                public int value;
            }
            """.trimIndent()

        @Language("Java")
        val badEmbedded =
            """
            package com.example;

            public class UnsupportedEmbedded {
                String name;
                CustomType custom;

                public UnsupportedEmbedded() {}
            }
            """.trimIndent()

        @Language("Java")
        val entitySource =
            """
            package com.example;
            import io.objectbox.annotation.Embedded;
            import io.objectbox.annotation.Entity;
            import io.objectbox.annotation.Id;

            @Entity
            public class UnsupportedEntity {
                @Id long id;
                @Embedded UnsupportedEmbedded embedded;

                public UnsupportedEntity() {}
            }
            """.trimIndent()

        TestEnvironment("embedded-error-type.json", useTemporaryModelFile = true)
            .apply {
                addSourceFile("com.example.CustomType", customType)
                addSourceFile("com.example.UnsupportedEmbedded", badEmbedded)
                addSourceFile("com.example.UnsupportedEntity", entitySource)
            }
            .compile()
            .assertThatIt {
                failed()
                hadErrorContaining("is not supported")
            }
    }
}
